name: usbnfcreader
description: "A new Flutter plugin project."
version: 0.0.2

environment:
    sdk: ^3.6.0-193.0.dev
    flutter: ">=3.3.0"

dependencies:
    flutter:
        sdk: flutter
    plugin_platform_interface: ^2.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    plugin:
        platforms:
            android:
                package: com.gms.usbnfcreader
                pluginClass: UsbnfcreaderPlugin
